export const LastMayday = (obj) => {
	return ({
		"width": "690rpx",
		"height": "934rpx",
		"background": "#FFFFFF",
		"views": [{
				"type": "text",
				"text": obj? obj.name : "totooooo",
				"css": {
					"color": "#333333",
					"background": "rgba(0,0,0,0)",
					"width": "690rpx",
					"height": "40.04rpx",
					"top": "178rpx",
					"left": "0rpx",
					"rotate": "0",
					"radius": "",
					"borderWidth": "",
					"borderColor": "#000000",
					"shadow": "",
					"padding": "0rpx",
					"fontSize": "28rpx",
					"fontWeight": "normal",
					"maxLines": "2",
					"lineHeight": "40.40400000000001rpx",
					"textStyle": "fill",
					"textDecoration": "none",
					"fontFamily": "",
					"textAlign": "center"
				}
			},
			{
				"type": "text",
				"text": "等，等等等等！",
				"css": {
					"color": "#F8AF24",
					"background": "rgba(0,0,0,0)",
					"width": "690rpx",
					"height": "40.04rpx",
					"top": "227rpx",
					"left": "0rpx",
					"rotate": "0",
					"radius": "",
					"borderWidth": "",
					"borderColor": "#000000",
					"shadow": "",
					"padding": "0rpx",
					"fontSize": "28rpx",
					"fontWeight": "normal",
					"maxLines": "2",
					"lineHeight": "40.40400000000001rpx",
					"textStyle": "fill",
					"textDecoration": "none",
					"fontFamily": "",
					"textAlign": "center"
				}
			},
			{
				"type": "image",
				"url": "https://img.jggjmm.com/uploads/files/20201021/471f89e3-f07b-4094-8fc2-0391a9bd4742.jpg",
				"css": {
					"width": "630rpx",
					"height": "170rpx",
					"top": "316rpx",
					"left": "29rpx",
					"rotate": "0",
					"radius": "3%",
					"borderWidth": "",
					"borderColor": "#000000",
					"shadow": "",
					"mode": "scaleToFill"
				}
			},
			{
				"type": "text",
				"text": obj? obj.text :"别跟我谈感情，谈感情伤钱。",
				"css": {
					"color": "#262626",
					"background": "rgba(0,0,0,0)",
					"width": "467rpx",
					"height": "34.32rpx",
					"top": "300rpx",
					"left": "114.25rpx",
					"rotate": "0",
					"radius": "",
					"borderWidth": "",
					"borderColor": "#000000",
					"shadow": "",
					"padding": "0rpx",
					"fontSize": "24rpx",
					"fontWeight": "normal",
					"maxLines": "2",
					"lineHeight": "34.632000000000005rpx",
					"textStyle": "fill",
					"textDecoration": "none",
					"fontFamily": "",
					"textAlign": "center"
				}
			},
			{
				"type": "text",
				"text": "30.00",
				"css": {
					"color": "#262626",
					"background": "rgba(0,0,0,0)",
					"width": "210rpx",
					"height": "40.04rpx",
					"top": "366rpx",
					"left": "33rpx",
					"rotate": "0",
					"radius": "",
					"borderWidth": "",
					"borderColor": "#000000",
					"shadow": "",
					"padding": "0rpx",
					"fontSize": "28rpx",
					"fontWeight": "normal",
					"maxLines": "2",
					"lineHeight": "40.40400000000001rpx",
					"textStyle": "fill",
					"textDecoration": "none",
					"fontFamily": "",
					"textAlign": "center"
				}
			},
			{
				"type": "text",
				"text": "@1.82",
				"css": {
					"color": "#34BE9A",
					"background": "rgba(0,0,0,0)",
					"width": "210rpx",
					"height": "40.04rpx",
					"top": "366rpx",
					"left": "244rpx",
					"rotate": "0",
					"radius": "",
					"borderWidth": "",
					"borderColor": "#000000",
					"shadow": "",
					"padding": "0rpx",
					"fontSize": "28rpx",
					"fontWeight": "normal",
					"maxLines": "2",
					"lineHeight": "40.40400000000001rpx",
					"textStyle": "fill",
					"textDecoration": "none",
					"fontFamily": "",
					"textAlign": "center"
				}
			},
			{
				"type": "text",
				"text": "JDG",
				"css": {
					"color": "#F8AF24",
					"background": "rgba(0,0,0,0)",
					"width": "210rpx",
					"height": "42.89999999999999rpx",
					"top": "366rpx",
					"left": "453rpx",
					"rotate": "0",
					"radius": "",
					"borderWidth": "",
					"borderColor": "#000000",
					"shadow": "",
					"padding": "0rpx",
					"fontSize": "30rpx",
					"fontWeight": "normal",
					"maxLines": "2",
					"lineHeight": "43.290000000000006rpx",
					"textStyle": "fill",
					"textDecoration": "none",
					"fontFamily": "",
					"textAlign": "center"
				}
			},
			{
				"type": "text",
				"text": "投注竞豆",
				"css": {
					"color": "#777777",
					"background": "rgba(0,0,0,0)",
					"width": "210rpx",
					"height": "34.32rpx",
					"top": "418rpx",
					"left": "35rpx",
					"rotate": "0",
					"radius": "",
					"borderWidth": "",
					"borderColor": "#000000",
					"shadow": "",
					"padding": "0rpx",
					"fontSize": "24rpx",
					"fontWeight": "normal",
					"maxLines": "2",
					"lineHeight": "34.632000000000005rpx",
					"textStyle": "fill",
					"textDecoration": "none",
					"fontFamily": "",
					"textAlign": "center"
				}
			},
			{
				"type": "text",
				"text": "赔率",
				"css": {
					"color": "#777777",
					"background": "rgba(0,0,0,0)",
					"width": "210rpx",
					"height": "34.32rpx",
					"top": "418rpx",
					"left": "244rpx",
					"rotate": "0",
					"radius": "",
					"borderWidth": "",
					"borderColor": "#000000",
					"shadow": "",
					"padding": "0rpx",
					"fontSize": "24rpx",
					"fontWeight": "normal",
					"maxLines": "2",
					"lineHeight": "34.632000000000005rpx",
					"textStyle": "fill",
					"textDecoration": "none",
					"fontFamily": "",
					"textAlign": "center"
				}
			},
			{
				"type": "image",
				"url": "https://image.xxe.io/data/upload/20170726/59784ce101002.png",
				"css": {
					"width": "36rpx",
					"height": "36rpx",
					"top": "553rpx",
					"left": "28rpx",
					"rotate": "0",
					"radius": "",
					"borderWidth": "",
					"borderColor": "#000000",
					"shadow": "",
					"mode": "scaleToFill"
				}
			},
			{
				"type": "view",
				"css": {
					"background": "#E9E9E9",
					"width": "690rpx",
					"height": "1rpx",
					"top": "521rpx",
					"left": "0rpx",
					"rotate": "0",
					"radius": "",
					"shadow": "",
					"color": "#E9E9E9"
				}
			},
			{
				"type": "view",
				"css": {
					"background": "#E9E9E9",
					"width": "690rpx",
					"height": "1rpx",
					"top": "751rpx",
					"left": "0rpx",
					"rotate": "0",
					"radius": "",
					"shadow": "",
					"color": "#E9E9E9"
				}
			},
			{
				"type": "text",
				"text": "BO3",
				"css": {
					"color": "#777777",
					"background": "rgba(0,0,0,0)",
					"width": "50rpx",
					"height": "31.459999999999997rpx",
					"top": "559rpx",
					"left": "345rpx",
					"rotate": "0",
					"radius": "",
					"borderWidth": "",
					"borderColor": "#000000",
					"shadow": "",
					"padding": "0rpx",
					"fontSize": "22rpx",
					"fontWeight": "normal",
					"maxLines": "2",
					"lineHeight": "31.746000000000006rpx",
					"textStyle": "fill",
					"textDecoration": "none",
					"fontFamily": "",
					"textAlign": "left"
				}
			},
			{
				"type": "text",
				"text": "完美世界亚洲ssssssss赛",
				"css": {
					"color": "#262626",
					"background": "rgba(0,0,0,0)",
					"width": "240rpx",
					"height": "27.119999999999997rpx",
					"top": "559rpx",
					"left": "74rpx",
					"rotate": "0",
					"radius": "",
					"borderWidth": "",
					"borderColor": "#000000",
					"shadow": "",
					"padding": "0rpx",
					"fontSize": "24rpx",
					"fontWeight": "normal",
					"maxLines": "1",
					"lineHeight": "26.64rpx",
					"textStyle": "fill",
					"textDecoration": "none",
					"fontFamily": "",
					"textAlign": "left"
				}
			},
			{
				"type": "text",
				"text": "2020-02-02 18:12",
				"css": {
					"color": "#333333",
					"background": "rgba(0,0,0,0)",
					"width": "200rpx",
					"height": "24.86rpx",
					"top": "559rpx",
					"left": "461rpx",
					"rotate": "0",
					"radius": "",
					"borderWidth": "",
					"borderColor": "#000000",
					"shadow": "",
					"padding": "0rpx",
					"fontSize": "22rpx",
					"fontWeight": "normal",
					"maxLines": "1",
					"lineHeight": "24.42rpx",
					"textStyle": "fill",
					"textDecoration": "none",
					"fontFamily": "",
					"textAlign": "center"
				}
			},
			{
				"type": "image",
				"url": "https://image.xxe.io/data/upload/20160916/57db897d3da50.png",
				"css": {
					"width": "66rpx",
					"height": "66rpx",
					"top": "611rpx",
					"left": "105rpx",
					"rotate": "0",
					"radius": "",
					"borderWidth": "",
					"borderColor": "#000000",
					"shadow": "",
					"mode": "scaleToFill"
				}
			},
			{
				"type": "image",
				"url": "https://image.xxe.io/data/upload/20170525/592635d417a65.png",
				"css": {
					"width": "66rpx",
					"height": "66rpx",
					"top": "611rpx",
					"left": "552rpx",
					"rotate": "0",
					"radius": "",
					"borderWidth": "",
					"borderColor": "#000000",
					"shadow": "",
					"mode": "scaleToFill"
				}
			},
			{
				"type": "text",
				"text": "3",
				"css": {
					"color": "#262626",
					"background": "rgba(0,0,0,0)",
					"width": "20.400000000000002rpx",
					"height": "38.419999999999995rpx",
					"top": "622rpx",
					"left": "266rpx",
					"rotate": "0",
					"radius": "",
					"borderWidth": "",
					"borderColor": "#000000",
					"shadow": "",
					"padding": "0rpx",
					"fontSize": "34rpx",
					"fontWeight": "normal",
					"maxLines": "1",
					"lineHeight": "37.74rpx",
					"textStyle": "fill",
					"textDecoration": "none",
					"fontFamily": "",
					"textAlign": "center"
				}
			},
			{
				"type": "text",
				"text": ":",
				"css": {
					"color": "#262626",
					"background": "rgba(0,0,0,0)",
					"width": "20rpx",
					"height": "38.419999999999995rpx",
					"top": "622rpx",
					"left": "360rpx",
					"rotate": "0",
					"radius": "",
					"borderWidth": "",
					"borderColor": "#000000",
					"shadow": "",
					"padding": "0rpx",
					"fontSize": "34rpx",
					"fontWeight": "normal",
					"maxLines": "1",
					"lineHeight": "37.74rpx",
					"textStyle": "fill",
					"textDecoration": "none",
					"fontFamily": "",
					"textAlign": "center"
				}
			},
			{
				"type": "text",
				"text": "0",
				"css": {
					"color": "#262626",
					"background": "rgba(0,0,0,0)",
					"width": "20.400000000000002rpx",
					"height": "38.419999999999995rpx",
					"top": "622rpx",
					"left": "463rpx",
					"rotate": "0",
					"radius": "",
					"borderWidth": "",
					"borderColor": "#000000",
					"shadow": "",
					"padding": "0rpx",
					"fontSize": "34rpx",
					"fontWeight": "normal",
					"maxLines": "1",
					"lineHeight": "37.74rpx",
					"textStyle": "fill",
					"textDecoration": "none",
					"fontFamily": "",
					"textAlign": "center"
				}
			},
			{
				"type": "image",
				"url": "http://img.jggjmm.com/uploads/files/20201022/8dd71488-1792-4873-8988-28053fa7a381.jpg",
				"css": {
					"width": "110rpx",
					"height": "110rpx",
					"top": "788rpx",
					"left": "30rpx",
					"rotate": "0",
					"radius": "",
					"borderWidth": "",
					"borderColor": "#000000",
					"shadow": "",
					"mode": "scaleToFill"
				}
			},
			{
				"type": "text",
				"text": "长按识别二维码，我们一起赚赚赚！",
				"css": {
					"color": "#333333",
					"background": "rgba(0,0,0,0)",
					"width": "400rpx",
					"height": "27.119999999999997rpx",
					"top": "850rpx",
					"left": "170rpx",
					"rotate": "0",
					"radius": "",
					"borderWidth": "",
					"borderColor": "#000000",
					"shadow": "",
					"padding": "0rpx",
					"fontSize": "24rpx",
					"fontWeight": "normal",
					"maxLines": "1",
					"lineHeight": "26.64rpx",
					"textStyle": "fill",
					"textDecoration": "none",
					"fontFamily": "",
					"textAlign": "left"
				}
			},
			{
				"type": "text",
				"text": "竞哥哥APP",
				"css": {
					"color": "#333333",
					"background": "rgba(0,0,0,0)",
					"width": "140rpx",
					"height": "31.639999999999997rpx",
					"top": "804rpx",
					"left": "170rpx",
					"rotate": "0",
					"radius": "",
					"borderWidth": "",
					"borderColor": "#000000",
					"shadow": "",
					"padding": "0rpx",
					"fontSize": "28rpx",
					"fontWeight": "normal",
					"maxLines": "1",
					"lineHeight": "31.080000000000002rpx",
					"textStyle": "fill",
					"textDecoration": "none",
					"fontFamily": "",
					"textAlign": "left"
				}
			},
			{
				"type": "text",
				"text": "投注选项",
				"css": {
					"color": "#777777",
					"background": "rgba(0,0,0,0)",
					"width": "210rpx",
					"height": "34.32rpx",
					"top": "418rpx",
					"left": "453rpx",
					"rotate": "0",
					"radius": "",
					"borderWidth": "",
					"borderColor": "#000000",
					"shadow": "",
					"padding": "0rpx",
					"fontSize": "24rpx",
					"fontWeight": "normal",
					"maxLines": "2",
					"lineHeight": "34.632000000000005rpx",
					"textStyle": "fill",
					"textDecoration": "none",
					"fontFamily": "",
					"textAlign": "center"
				}
			},
			{
				"type": "image",
				"url": obj? obj.userImg : "https://img.jggjmm.com/uploads/files/20200923/3aaefe24-31a7-466c-9ad0-dfd11b2463cb.png",
				"css": {
					"width": "136rpx",
					"height": "136rpx",
					"top": "30rpx",
					"left": "279rpx",
					"rotate": "0",
					"radius": "50%",
					"borderWidth": "",
					"borderColor": "#000000",
					"shadow": "",
					"mode": "scaleToFill"
				}
			},
			{
				"type": "text",
				"text": "G2",
				"css": {
					"color": "#262626",
					"background": "rgba(0,0,0,0)",
					"width": "200rpx",
					"height": "27.119999999999997rpx",
					"top": "689rpx",
					"left": "37rpx",
					"rotate": "0",
					"radius": "",
					"borderWidth": "",
					"borderColor": "#000000",
					"shadow": "",
					"padding": "0rpx",
					"fontSize": "24rpx",
					"fontWeight": "normal",
					"maxLines": "1",
					"lineHeight": "26.64rpx",
					"textStyle": "fill",
					"textDecoration": "none",
					"fontFamily": "",
					"textAlign": "center"
				}
			},
			{
				"type": "text",
				"text": "JDG",
				"css": {
					"color": "#262626",
					"background": "rgba(0,0,0,0)",
					"width": "200rpx",
					"height": "27.119999999999997rpx",
					"top": "689rpx",
					"left": "486rpx",
					"rotate": "0",
					"radius": "",
					"borderWidth": "",
					"borderColor": "#000000",
					"shadow": "",
					"padding": "0rpx",
					"fontSize": "24rpx",
					"fontWeight": "normal",
					"maxLines": "1",
					"lineHeight": "26.64rpx",
					"textStyle": "fill",
					"textDecoration": "none",
					"fontFamily": "",
					"textAlign": "center"
				}
			}
		]
	});
}
